// Mocks generated by Mockito 5.4.4 from annotations
// in pol_lapor/test/unit/auth_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i9;

import 'package:flutter/foundation.dart' as _i3;
import 'package:hive_flutter/hive_flutter.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i13;
import 'package:pol_lapor/data/datasources/local/auth_local_datasource.dart'
    as _i4;
import 'package:pol_lapor/data/datasources/remote/auth_remote_datasource.dart'
    as _i6;
import 'package:pol_lapor/data/models/laporan_lokal.dart' as _i11;
import 'package:pol_lapor/data/models/notifikasi.dart' as _i8;
import 'package:pol_lapor/data/models/user_session.dart' as _i2;
import 'package:pol_lapor/logic/providers/laporan_provider.dart' as _i10;
import 'package:pol_lapor/logic/providers/notifikasi_provider.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserSession_0 extends _i1.SmartFake implements _i2.UserSession {
  _FakeUserSession_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeValueListenable_1<T> extends _i1.SmartFake
    implements _i3.ValueListenable<T> {
  _FakeValueListenable_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDatasource extends _i1.Mock
    implements _i4.AuthLocalDatasource {
  MockAuthLocalDatasource();

  @override
  _i5.Future<void> saveSession(_i2.UserSession? session) => (super.noSuchMethod(
        Invocation.method(
          #saveSession,
          [session],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  bool isLoggedIn() => (super.noSuchMethod(
        Invocation.method(
          #isLoggedIn,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i2.UserSession? getSession() => (super.noSuchMethod(
        Invocation.method(
          #getSession,
          [],
        ),
        returnValue: null,
      ) as _i2.UserSession?);

  @override
  _i5.Future<void> clearSession() => (super.noSuchMethod(
        Invocation.method(
          #clearSession,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [AuthRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDatasource extends _i1.Mock
    implements _i6.AuthRemoteDatasource {
  MockAuthRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.UserSession> register({
    required String? namaLengkap,
    required String? email,
    required String? password,
    String? nomorTelepon,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {
            #namaLengkap: namaLengkap,
            #email: email,
            #password: password,
            #nomorTelepon: nomorTelepon,
          },
        ),
        returnValue: _i5.Future<_i2.UserSession>.value(_FakeUserSession_0(
          this,
          Invocation.method(
            #register,
            [],
            {
              #namaLengkap: namaLengkap,
              #email: email,
              #password: password,
              #nomorTelepon: nomorTelepon,
            },
          ),
        )),
      ) as _i5.Future<_i2.UserSession>);

  @override
  _i5.Future<_i2.UserSession> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue: _i5.Future<_i2.UserSession>.value(_FakeUserSession_0(
          this,
          Invocation.method(
            #login,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i5.Future<_i2.UserSession>);

  @override
  _i5.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updatePassword(
    String? email,
    String? oldPassword,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePassword,
          [
            email,
            oldPassword,
            newPassword,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateNamaLengkap(
    String? userId,
    String? namaLengkap,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateNamaLengkap,
          [
            userId,
            namaLengkap,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.UserSession?> getSessionFromSupabase() => (super.noSuchMethod(
        Invocation.method(
          #getSessionFromSupabase,
          [],
        ),
        returnValue: _i5.Future<_i2.UserSession?>.value(),
      ) as _i5.Future<_i2.UserSession?>);
}

/// A class which mocks [NotifikasiProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotifikasiProvider extends _i1.Mock
    implements _i7.NotifikasiProvider {
  MockNotifikasiProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i8.Notifikasi> get notifikasiList => (super.noSuchMethod(
        Invocation.getter(#notifikasiList),
        returnValue: <_i8.Notifikasi>[],
      ) as List<_i8.Notifikasi>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  int get unreadCount => (super.noSuchMethod(
        Invocation.getter(#unreadCount),
        returnValue: 0,
      ) as int);

  @override
  List<_i8.Notifikasi> get unreadList => (super.noSuchMethod(
        Invocation.getter(#unreadList),
        returnValue: <_i8.Notifikasi>[],
      ) as List<_i8.Notifikasi>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> init(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #init,
          [userId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> fetchNotifikasi() => (super.noSuchMethod(
        Invocation.method(
          #fetchNotifikasi,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> markAsRead(String? notifikasiId) => (super.noSuchMethod(
        Invocation.method(
          #markAsRead,
          [notifikasiId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> markAllAsRead() => (super.noSuchMethod(
        Invocation.method(
          #markAllAsRead,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteNotifikasi(String? notifikasiId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteNotifikasi,
          [notifikasiId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> kirimNotifikasi({
    required String? penerimaId,
    required String? judul,
    required String? pesan,
    required String? tipe,
    String? formulirId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #kirimNotifikasi,
          [],
          {
            #penerimaId: penerimaId,
            #judul: judul,
            #pesan: pesan,
            #tipe: tipe,
            #formulirId: formulirId,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void reset() => super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [LaporanProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockLaporanProvider extends _i1.Mock implements _i10.LaporanProvider {
  MockLaporanProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i11.LaporanLokal> get laporanList => (super.noSuchMethod(
        Invocation.getter(#laporanList),
        returnValue: <_i11.LaporanLokal>[],
      ) as List<_i11.LaporanLokal>);

  @override
  _i3.ValueListenable<_i12.Box<_i11.LaporanLokal>> get laporanListenable =>
      (super.noSuchMethod(
        Invocation.getter(#laporanListenable),
        returnValue: _FakeValueListenable_1<_i12.Box<_i11.LaporanLokal>>(
          this,
          Invocation.getter(#laporanListenable),
        ),
      ) as _i3.ValueListenable<_i12.Box<_i11.LaporanLokal>>);

  @override
  int get totalLaporan => (super.noSuchMethod(
        Invocation.getter(#totalLaporan),
        returnValue: 0,
      ) as int);

  @override
  int get totalUnsynced => (super.noSuchMethod(
        Invocation.getter(#totalUnsynced),
        returnValue: 0,
      ) as int);

  @override
  int get totalDiproses => (super.noSuchMethod(
        Invocation.getter(#totalDiproses),
        returnValue: 0,
      ) as int);

  @override
  int get totalSelesai => (super.noSuchMethod(
        Invocation.getter(#totalSelesai),
        returnValue: 0,
      ) as int);

  @override
  int get totalMenunggu => (super.noSuchMethod(
        Invocation.getter(#totalMenunggu),
        returnValue: 0,
      ) as int);

  @override
  int get totalDitolak => (super.noSuchMethod(
        Invocation.getter(#totalDitolak),
        returnValue: 0,
      ) as int);

  @override
  int get totalEskalasi => (super.noSuchMethod(
        Invocation.getter(#totalEskalasi),
        returnValue: 0,
      ) as int);

  @override
  String get namaUser => (super.noSuchMethod(
        Invocation.getter(#namaUser),
        returnValue: _i13.dummyValue<String>(
          this,
          Invocation.getter(#namaUser),
        ),
      ) as String);

  @override
  String get roleUser => (super.noSuchMethod(
        Invocation.getter(#roleUser),
        returnValue: _i13.dummyValue<String>(
          this,
          Invocation.getter(#roleUser),
        ),
      ) as String);

  @override
  String get emailUser => (super.noSuchMethod(
        Invocation.getter(#emailUser),
        returnValue: _i13.dummyValue<String>(
          this,
          Invocation.getter(#emailUser),
        ),
      ) as String);

  @override
  List<_i11.LaporanLokal> get laporanPublik => (super.noSuchMethod(
        Invocation.getter(#laporanPublik),
        returnValue: <_i11.LaporanLokal>[],
      ) as List<_i11.LaporanLokal>);

  @override
  bool get isLoadingPublik => (super.noSuchMethod(
        Invocation.getter(#isLoadingPublik),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void init() => super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void refreshSession() => super.noSuchMethod(
        Invocation.method(
          #refreshSession,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> syncFromRemote() => (super.noSuchMethod(
        Invocation.method(
          #syncFromRemote,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> fetchLaporanPublik() => (super.noSuchMethod(
        Invocation.method(
          #fetchLaporanPublik,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  List<_i11.LaporanLokal> recentLaporan({int? limit = 3}) =>
      (super.noSuchMethod(
        Invocation.method(
          #recentLaporan,
          [],
          {#limit: limit},
        ),
        returnValue: <_i11.LaporanLokal>[],
      ) as List<_i11.LaporanLokal>);

  @override
  _i11.LaporanLokal? getLaporanById(String? formulirId) =>
      (super.noSuchMethod(Invocation.method(
        #getLaporanById,
        [formulirId],
      )) as _i11.LaporanLokal?);

  @override
  List<_i11.LaporanLokal> filterLaporan({
    String? filterStatus = r'semua',
    String? searchQuery = r'',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #filterLaporan,
          [],
          {
            #filterStatus: filterStatus,
            #searchQuery: searchQuery,
          },
        ),
        returnValue: <_i11.LaporanLokal>[],
      ) as List<_i11.LaporanLokal>);

  @override
  void onReturnFromForm() => super.noSuchMethod(
        Invocation.method(
          #onReturnFromForm,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool isOwner(_i11.LaporanLokal? laporan) => (super.noSuchMethod(
        Invocation.method(
          #isOwner,
          [laporan],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool canDelete(_i11.LaporanLokal? laporan) => (super.noSuchMethod(
        Invocation.method(
          #canDelete,
          [laporan],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool canEdit(_i11.LaporanLokal? laporan) => (super.noSuchMethod(
        Invocation.method(
          #canEdit,
          [laporan],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> deleteLaporan(_i11.LaporanLokal? laporan) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteLaporan,
          [laporan],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
