// Mocks generated by Mockito 5.4.4 from annotations
// in pol_lapor/test/unit/mock_datasources.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pol_lapor/data/datasources/remote/notifikasi_remote_datasource.dart'
    as _i9;
import 'package:pol_lapor/data/datasources/remote/penanganan_remote_datasource.dart'
    as _i3;
import 'package:pol_lapor/data/datasources/remote/storage_remote_datasource.dart'
    as _i8;
import 'package:pol_lapor/data/datasources/remote/tracking_remote_datasource.dart'
    as _i6;
import 'package:pol_lapor/data/models/laporan_lokal.dart' as _i5;
import 'package:pol_lapor/data/models/notifikasi.dart' as _i10;
import 'package:pol_lapor/data/models/tracking.dart' as _i7;
import 'package:supabase_flutter/supabase_flutter.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRealtimeChannel_0 extends _i1.SmartFake
    implements _i2.RealtimeChannel {
  _FakeRealtimeChannel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PenangananRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPenangananRemoteDatasource extends _i1.Mock
    implements _i3.PenangananRemoteDatasource {
  MockPenangananRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<Map<String, dynamic>>> fetchPenangananRows(
          String? teknisiId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchPenangananRows,
          [teknisiId],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, dynamic>?> fetchPenangananByFormulir(
          String? formulirId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchPenangananByFormulir,
          [formulirId],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<Map<String, int>> fetchStats(String? teknisiId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchStats,
          [teknisiId],
        ),
        returnValue: _i4.Future<Map<String, int>>.value(<String, int>{}),
      ) as _i4.Future<Map<String, int>>);

  @override
  _i4.Future<List<_i5.LaporanLokal>> fetchDaftarTugas(String? teknisiId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchDaftarTugas,
          [teknisiId],
        ),
        returnValue:
            _i4.Future<List<_i5.LaporanLokal>>.value(<_i5.LaporanLokal>[]),
      ) as _i4.Future<List<_i5.LaporanLokal>>);

  @override
  _i4.Future<List<_i5.LaporanLokal>> fetchLaporanTerbaru(
    String? teknisiId, {
    int? limit = 5,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchLaporanTerbaru,
          [teknisiId],
          {#limit: limit},
        ),
        returnValue:
            _i4.Future<List<_i5.LaporanLokal>>.value(<_i5.LaporanLokal>[]),
      ) as _i4.Future<List<_i5.LaporanLokal>>);

  @override
  _i4.Future<void> insertPenanganan(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertPenanganan,
          [data],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updatePenanganan(
    String? penangananId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePenanganan,
          [
            penangananId,
            data,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateStatusFormulir(
    String? formulirId,
    String? status, {
    String? updatedAt,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStatusFormulir,
          [
            formulirId,
            status,
          ],
          {#updatedAt: updatedAt},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [TrackingRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTrackingRemoteDatasource extends _i1.Mock
    implements _i6.TrackingRemoteDatasource {
  MockTrackingRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isListening => (super.noSuchMethod(
        Invocation.getter(#isListening),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> catatTracking({
    required String? formulirId,
    String? aktorId,
    required String? jenisEvent,
    required String? pesanNarasi,
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #catatTracking,
          [],
          {
            #formulirId: formulirId,
            #aktorId: aktorId,
            #jenisEvent: jenisEvent,
            #pesanNarasi: pesanNarasi,
            #metadata: metadata,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i7.Tracking>> fetchRiwayatTracking(String? formulirId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchRiwayatTracking,
          [formulirId],
        ),
        returnValue: _i4.Future<List<_i7.Tracking>>.value(<_i7.Tracking>[]),
      ) as _i4.Future<List<_i7.Tracking>>);

  @override
  void subscribeRealtime({
    required String? formulirId,
    required void Function(_i7.Tracking)? onNewTracking,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #subscribeRealtime,
          [],
          {
            #formulirId: formulirId,
            #onNewTracking: onNewTracking,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unsubscribe() => super.noSuchMethod(
        Invocation.method(
          #unsubscribe,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [StorageRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageRemoteDatasource extends _i1.Mock
    implements _i8.StorageRemoteDatasource {
  MockStorageRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String?> uploadFotoKerusakan({
    required String? filePath,
    required String? formulirId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFotoKerusakan,
          [],
          {
            #filePath: filePath,
            #formulirId: formulirId,
          },
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<String?> uploadFotoProgres({
    required String? filePath,
    required String? formulirId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFotoProgres,
          [],
          {
            #filePath: filePath,
            #formulirId: formulirId,
          },
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);
}

/// A class which mocks [NotifikasiRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotifikasiRemoteDatasource extends _i1.Mock
    implements _i9.NotifikasiRemoteDatasource {
  MockNotifikasiRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i10.Notifikasi>> fetchNotifikasiUser(String? penerimaId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchNotifikasiUser,
          [penerimaId],
        ),
        returnValue:
            _i4.Future<List<_i10.Notifikasi>>.value(<_i10.Notifikasi>[]),
      ) as _i4.Future<List<_i10.Notifikasi>>);

  @override
  _i4.Future<int> fetchUnreadCount(String? penerimaId) => (super.noSuchMethod(
        Invocation.method(
          #fetchUnreadCount,
          [penerimaId],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<void> insertNotifikasi({
    required String? penerimaId,
    required String? judul,
    required String? pesan,
    required String? tipe,
    String? formulirId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertNotifikasi,
          [],
          {
            #penerimaId: penerimaId,
            #judul: judul,
            #pesan: pesan,
            #tipe: tipe,
            #formulirId: formulirId,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> markAsRead(String? notifikasiId) => (super.noSuchMethod(
        Invocation.method(
          #markAsRead,
          [notifikasiId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> markAllAsRead(String? penerimaId) => (super.noSuchMethod(
        Invocation.method(
          #markAllAsRead,
          [penerimaId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteNotifikasi(String? notifikasiId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteNotifikasi,
          [notifikasiId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i2.RealtimeChannel subscribeToUserNotifikasi({
    required String? penerimaId,
    required void Function(_i10.Notifikasi)? onNew,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribeToUserNotifikasi,
          [],
          {
            #penerimaId: penerimaId,
            #onNew: onNew,
          },
        ),
        returnValue: _FakeRealtimeChannel_0(
          this,
          Invocation.method(
            #subscribeToUserNotifikasi,
            [],
            {
              #penerimaId: penerimaId,
              #onNew: onNew,
            },
          ),
        ),
      ) as _i2.RealtimeChannel);
}
