// Mocks generated by Mockito 5.4.4 from annotations
// in pol_lapor/test/logic/providers/form_laporan_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter/foundation.dart' as _i2;
import 'package:hive_flutter/hive_flutter.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pol_lapor/data/datasources/local/laporan_local_datasource.dart'
    as _i3;
import 'package:pol_lapor/data/datasources/remote/laporan_remote_datasource.dart'
    as _i7;
import 'package:pol_lapor/data/datasources/remote/storage_remote_datasource.dart'
    as _i8;
import 'package:pol_lapor/data/models/laporan_lokal.dart' as _i5;
import 'package:pol_lapor/services/sync_service.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeValueListenable_0<T> extends _i1.SmartFake
    implements _i2.ValueListenable<T> {
  _FakeValueListenable_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LaporanLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLaporanLocalDatasource extends _i1.Mock
    implements _i3.LaporanLocalDatasource {
  MockLaporanLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveLaporan(_i5.LaporanLokal? laporan) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveLaporan,
          [laporan],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  List<_i5.LaporanLokal> getAllLaporan() => (super.noSuchMethod(
        Invocation.method(
          #getAllLaporan,
          [],
        ),
        returnValue: <_i5.LaporanLokal>[],
      ) as List<_i5.LaporanLokal>);

  @override
  List<_i5.LaporanLokal> getUnsyncedLaporan() => (super.noSuchMethod(
        Invocation.method(
          #getUnsyncedLaporan,
          [],
        ),
        returnValue: <_i5.LaporanLokal>[],
      ) as List<_i5.LaporanLokal>);

  @override
  _i5.LaporanLokal? getLaporanById(String? formulirId) =>
      (super.noSuchMethod(Invocation.method(
        #getLaporanById,
        [formulirId],
      )) as _i5.LaporanLokal?);

  @override
  _i4.Future<void> updateLaporan(_i5.LaporanLokal? laporan) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLaporan,
          [laporan],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteLaporan(String? formulirId) => (super.noSuchMethod(
        Invocation.method(
          #deleteLaporan,
          [formulirId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> markSynced(String? formulirId) => (super.noSuchMethod(
        Invocation.method(
          #markSynced,
          [formulirId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> markAsSynced(
    String? formulirId,
    String? fotoCloudUrl,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAsSynced,
          [
            formulirId,
            fotoCloudUrl,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateStatus(
    String? formulirId,
    String? statusBaru,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStatus,
          [
            formulirId,
            statusBaru,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  int countAll() => (super.noSuchMethod(
        Invocation.method(
          #countAll,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  int countUnsynced() => (super.noSuchMethod(
        Invocation.method(
          #countUnsynced,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  _i2.ValueListenable<_i6.Box<_i5.LaporanLokal>> listenable() =>
      (super.noSuchMethod(
        Invocation.method(
          #listenable,
          [],
        ),
        returnValue: _FakeValueListenable_0<_i6.Box<_i5.LaporanLokal>>(
          this,
          Invocation.method(
            #listenable,
            [],
          ),
        ),
      ) as _i2.ValueListenable<_i6.Box<_i5.LaporanLokal>>);

  @override
  List<_i5.LaporanLokal> getLaporanAktifByLokasi(String? lokasi) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLaporanAktifByLokasi,
          [lokasi],
        ),
        returnValue: <_i5.LaporanLokal>[],
      ) as List<_i5.LaporanLokal>);

  @override
  _i4.Future<void> syncFromRemote(
    List<Map<String, dynamic>>? remoteLaporan,
    String? pelaporId, {
    bool? isFullSync = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncFromRemote,
          [
            remoteLaporan,
            pelaporId,
          ],
          {#isFullSync: isFullSync},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [LaporanRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLaporanRemoteDatasource extends _i1.Mock
    implements _i7.LaporanRemoteDatasource {
  MockLaporanRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<int?> countLaporanAktifByLokasi(String? namaRuangan) =>
      (super.noSuchMethod(
        Invocation.method(
          #countLaporanAktifByLokasi,
          [namaRuangan],
        ),
        returnValue: _i4.Future<int?>.value(),
      ) as _i4.Future<int?>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getLaporanAktifByLokasi(
          String? namaRuangan) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLaporanAktifByLokasi,
          [namaRuangan],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<void> deleteLaporan({
    required String? formulirId,
    required String? pelaporId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteLaporan,
          [],
          {
            #formulirId: formulirId,
            #pelaporId: pelaporId,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateLaporanRemote({
    required String? formulirId,
    required String? namaSarana,
    required String? keteranganKerusakan,
    String? namaRuangan,
    String? nomorInventaris,
    String? fotoUrl,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateLaporanRemote,
          [],
          {
            #formulirId: formulirId,
            #namaSarana: namaSarana,
            #keteranganKerusakan: keteranganKerusakan,
            #namaRuangan: namaRuangan,
            #nomorInventaris: nomorInventaris,
            #fotoUrl: fotoUrl,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<Map<String, dynamic>>> fetchLaporanByPelapor(
          String? pelaporId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchLaporanByPelapor,
          [pelaporId],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> fetchAllLaporan() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchAllLaporan,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [StorageRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageRemoteDatasource extends _i1.Mock
    implements _i8.StorageRemoteDatasource {
  MockStorageRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String?> uploadFotoKerusakan({
    required String? filePath,
    required String? formulirId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFotoKerusakan,
          [],
          {
            #filePath: filePath,
            #formulirId: formulirId,
          },
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<String?> uploadFotoProgres({
    required String? filePath,
    required String? formulirId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFotoProgres,
          [],
          {
            #filePath: filePath,
            #formulirId: formulirId,
          },
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);
}

/// A class which mocks [SyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSyncService extends _i1.Mock implements _i9.SyncService {
  MockSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void startAutoSync() => super.noSuchMethod(
        Invocation.method(
          #startAutoSync,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void stopAutoSync() => super.noSuchMethod(
        Invocation.method(
          #stopAutoSync,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> syncUnsyncedData() => (super.noSuchMethod(
        Invocation.method(
          #syncUnsyncedData,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
